global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'price'
    # Actuator end point to collect the data.
    metrics_path: 'price-hist/actuator/prometheus'
    #How frequently to scape the data from the end point
    scrape_interval: 5s
    #target end point. We are using the Docker, so local host will not work. You can change it with
    #localhost if not using the Docker.
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8080' ]
